### ISSUE TITLE
no api for fetch Teams list name.

### ISSUE THREAD

**Issue by eliavmaman** [kambi-sportsbook-widgets/widget-core-library#3]
I would like to fetch team names list so i can filter events by team.
I've look in offeringModule but couldn't find such API.
WHat to do?

**Comment by owain-stratton** [comment]
The offeringModule is an interface between the Kambi Offering API V2/V3 these two versions are undocumented by Kambi so you would need to work out which endpoints to hit and perform all the logic yourself. 

We are currently updating the offeringModule to the new V2018 Offering API that is documented here: https://e1-api.kambi.com/offering/v2018/docs/#/docs/intro/overview

In the meantime you could use this directly and look at the endpoints to determine how you can get teams mapped.

**Comment by eliavmaman** [comment]
@owain-stratton So how can i get the list of football teams per league? Can u please help us with reference  to another API?

**Comment by eliavmaman** [comment]
@owain-stratton ?

**Comment by owain-stratton** [comment]
Tricky one, maybe check out the data fetching logic in this widget https://github.com/kambi-sportsbook-widgets/league-table-widget

This displays a league table with the teams within that league, you could probably use some of the code. 

**NOTE:** this widget uses the undocumented V2 and V3 Kambi offering APIs you should try and rework it for the V2018 api based on the docs in the comment above.

**Comment by eliavmaman** [comment]
@owain-stratton  10x man i'll look at it
